/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface EscapableInterface extends utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "changeOwnership(address)": FunctionFragment;
    "escapeHatchCaller()": FunctionFragment;
    "escapeHatchDestination()": FunctionFragment;
    "newOwnerCandidate()": FunctionFragment;
    "owner()": FunctionFragment;
    "proposeOwnership(address)": FunctionFragment;
    "removeOwnership(address)": FunctionFragment;
    "isTokenEscapable(address)": FunctionFragment;
    "escapeHatch(address)": FunctionFragment;
    "changeHatchEscapeCaller(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOwnership"
      | "changeOwnership"
      | "escapeHatchCaller"
      | "escapeHatchDestination"
      | "newOwnerCandidate"
      | "owner"
      | "proposeOwnership"
      | "removeOwnership"
      | "isTokenEscapable"
      | "escapeHatch"
      | "changeHatchEscapeCaller"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "escapeHatchCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escapeHatchDestination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "newOwnerCandidate",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenEscapable",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "escapeHatch",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "changeHatchEscapeCaller",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escapeHatchCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escapeHatchDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newOwnerCandidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenEscapable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escapeHatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeHatchEscapeCaller",
    data: BytesLike
  ): Result;

  events: {
    "EscapeHatchBlackistedToken(address)": EventFragment;
    "EscapeHatchCalled(address,uint256)": EventFragment;
    "OwnershipRemoved()": EventFragment;
    "OwnershipRequested(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EscapeHatchBlackistedToken"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EscapeHatchCalled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface EscapeHatchBlackistedTokenEventObject {
  token: string;
}
export type EscapeHatchBlackistedTokenEvent = TypedEvent<
  [string],
  EscapeHatchBlackistedTokenEventObject
>;

export type EscapeHatchBlackistedTokenEventFilter =
  TypedEventFilter<EscapeHatchBlackistedTokenEvent>;

export interface EscapeHatchCalledEventObject {
  token: string;
  amount: BigNumber;
}
export type EscapeHatchCalledEvent = TypedEvent<
  [string, BigNumber],
  EscapeHatchCalledEventObject
>;

export type EscapeHatchCalledEventFilter =
  TypedEventFilter<EscapeHatchCalledEvent>;

export interface OwnershipRemovedEventObject {}
export type OwnershipRemovedEvent = TypedEvent<[], OwnershipRemovedEventObject>;

export type OwnershipRemovedEventFilter =
  TypedEventFilter<OwnershipRemovedEvent>;

export interface OwnershipRequestedEventObject {
  by: string;
  to: string;
}
export type OwnershipRequestedEvent = TypedEvent<
  [string, string],
  OwnershipRequestedEventObject
>;

export type OwnershipRequestedEventFilter =
  TypedEventFilter<OwnershipRequestedEvent>;

export interface OwnershipTransferredEventObject {
  from: string;
  to: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Escapable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EscapableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Can only be called by the `newOwnerCandidate`, accepts the  transfer of ownership
     */
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * In this 2nd option for ownership transfer `changeOwnership()` can  be called and it will immediately assign ownership to the `newOwner`
     * `owner` can step down and assign some other address to this role
     * @param _newOwner The address of the new owner
     */
    changeOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    escapeHatchCaller(overrides?: CallOverrides): Promise<[string]>;

    escapeHatchDestination(overrides?: CallOverrides): Promise<[string]>;

    newOwnerCandidate(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    /**
     * In this 1st option for ownership transfer `proposeOwnership()` must  be called first by the current `owner` then `acceptOwnership()` must be  called by the `newOwnerCandidate`
     * `onlyOwner` Proposes to transfer control of the contract to a  new owner
     * @param _newOwnerCandidate The address being proposed as the new owner
     */
    proposeOwnership(
      _newOwnerCandidate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * In this 3rd option for ownership transfer `removeOwnership()` can  be called and it will immediately assign ownership to the 0x0 address;  it requires a 0xdece be input as a parameter to prevent accidental use
     * Decentralizes the contract, this operation cannot be undone
     * @param _dac `0xdac` has to be entered for this function to work
     */
    removeOwnership(
      _dac: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * Checks to see if `_token` is in the blacklist of tokens
     * @param _token the token address being queried
     * @returns False if `_token` is in the blacklist and can't be taken out of  the contract via the `escapeHatch()`
     */
    isTokenEscapable(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * The `escapeHatch()` should only be called as a last resort if a security issue is uncovered or something unexpected happened
     * @param _token to transfer, use 0x0 for ether
     */
    escapeHatch(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * Changes the address assigned to call `escapeHatch()`
     * @param _newEscapeHatchCaller The address of a trusted account or  contract to call `escapeHatch()` to send the value in this contract to  the `escapeHatchDestination`; it would be ideal that `escapeHatchCaller`  cannot move funds out of `escapeHatchDestination`
     */
    changeHatchEscapeCaller(
      _newEscapeHatchCaller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  /**
   * Can only be called by the `newOwnerCandidate`, accepts the  transfer of ownership
   */
  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * In this 2nd option for ownership transfer `changeOwnership()` can  be called and it will immediately assign ownership to the `newOwner`
   * `owner` can step down and assign some other address to this role
   * @param _newOwner The address of the new owner
   */
  changeOwnership(
    _newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  escapeHatchCaller(overrides?: CallOverrides): Promise<string>;

  escapeHatchDestination(overrides?: CallOverrides): Promise<string>;

  newOwnerCandidate(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  /**
   * In this 1st option for ownership transfer `proposeOwnership()` must  be called first by the current `owner` then `acceptOwnership()` must be  called by the `newOwnerCandidate`
   * `onlyOwner` Proposes to transfer control of the contract to a  new owner
   * @param _newOwnerCandidate The address being proposed as the new owner
   */
  proposeOwnership(
    _newOwnerCandidate: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * In this 3rd option for ownership transfer `removeOwnership()` can  be called and it will immediately assign ownership to the 0x0 address;  it requires a 0xdece be input as a parameter to prevent accidental use
   * Decentralizes the contract, this operation cannot be undone
   * @param _dac `0xdac` has to be entered for this function to work
   */
  removeOwnership(
    _dac: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * Checks to see if `_token` is in the blacklist of tokens
   * @param _token the token address being queried
   * @returns False if `_token` is in the blacklist and can't be taken out of  the contract via the `escapeHatch()`
   */
  isTokenEscapable(
    _token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * The `escapeHatch()` should only be called as a last resort if a security issue is uncovered or something unexpected happened
   * @param _token to transfer, use 0x0 for ether
   */
  escapeHatch(
    _token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * Changes the address assigned to call `escapeHatch()`
   * @param _newEscapeHatchCaller The address of a trusted account or  contract to call `escapeHatch()` to send the value in this contract to  the `escapeHatchDestination`; it would be ideal that `escapeHatchCaller`  cannot move funds out of `escapeHatchDestination`
   */
  changeHatchEscapeCaller(
    _newEscapeHatchCaller: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Can only be called by the `newOwnerCandidate`, accepts the  transfer of ownership
     */
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    /**
     * In this 2nd option for ownership transfer `changeOwnership()` can  be called and it will immediately assign ownership to the `newOwner`
     * `owner` can step down and assign some other address to this role
     * @param _newOwner The address of the new owner
     */
    changeOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    escapeHatchCaller(overrides?: CallOverrides): Promise<string>;

    escapeHatchDestination(overrides?: CallOverrides): Promise<string>;

    newOwnerCandidate(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    /**
     * In this 1st option for ownership transfer `proposeOwnership()` must  be called first by the current `owner` then `acceptOwnership()` must be  called by the `newOwnerCandidate`
     * `onlyOwner` Proposes to transfer control of the contract to a  new owner
     * @param _newOwnerCandidate The address being proposed as the new owner
     */
    proposeOwnership(
      _newOwnerCandidate: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * In this 3rd option for ownership transfer `removeOwnership()` can  be called and it will immediately assign ownership to the 0x0 address;  it requires a 0xdece be input as a parameter to prevent accidental use
     * Decentralizes the contract, this operation cannot be undone
     * @param _dac `0xdac` has to be entered for this function to work
     */
    removeOwnership(
      _dac: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Checks to see if `_token` is in the blacklist of tokens
     * @param _token the token address being queried
     * @returns False if `_token` is in the blacklist and can't be taken out of  the contract via the `escapeHatch()`
     */
    isTokenEscapable(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * The `escapeHatch()` should only be called as a last resort if a security issue is uncovered or something unexpected happened
     * @param _token to transfer, use 0x0 for ether
     */
    escapeHatch(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Changes the address assigned to call `escapeHatch()`
     * @param _newEscapeHatchCaller The address of a trusted account or  contract to call `escapeHatch()` to send the value in this contract to  the `escapeHatchDestination`; it would be ideal that `escapeHatchCaller`  cannot move funds out of `escapeHatchDestination`
     */
    changeHatchEscapeCaller(
      _newEscapeHatchCaller: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "EscapeHatchBlackistedToken(address)"(
      token?: null
    ): EscapeHatchBlackistedTokenEventFilter;
    EscapeHatchBlackistedToken(
      token?: null
    ): EscapeHatchBlackistedTokenEventFilter;

    "EscapeHatchCalled(address,uint256)"(
      token?: null,
      amount?: null
    ): EscapeHatchCalledEventFilter;
    EscapeHatchCalled(
      token?: null,
      amount?: null
    ): EscapeHatchCalledEventFilter;

    "OwnershipRemoved()"(): OwnershipRemovedEventFilter;
    OwnershipRemoved(): OwnershipRemovedEventFilter;

    "OwnershipRequested(address,address)"(
      by?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipRequestedEventFilter;
    OwnershipRequested(
      by?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipRequestedEventFilter;

    "OwnershipTransferred(address,address)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    /**
     * Can only be called by the `newOwnerCandidate`, accepts the  transfer of ownership
     */
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * In this 2nd option for ownership transfer `changeOwnership()` can  be called and it will immediately assign ownership to the `newOwner`
     * `owner` can step down and assign some other address to this role
     * @param _newOwner The address of the new owner
     */
    changeOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    escapeHatchCaller(overrides?: CallOverrides): Promise<BigNumber>;

    escapeHatchDestination(overrides?: CallOverrides): Promise<BigNumber>;

    newOwnerCandidate(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    /**
     * In this 1st option for ownership transfer `proposeOwnership()` must  be called first by the current `owner` then `acceptOwnership()` must be  called by the `newOwnerCandidate`
     * `onlyOwner` Proposes to transfer control of the contract to a  new owner
     * @param _newOwnerCandidate The address being proposed as the new owner
     */
    proposeOwnership(
      _newOwnerCandidate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * In this 3rd option for ownership transfer `removeOwnership()` can  be called and it will immediately assign ownership to the 0x0 address;  it requires a 0xdece be input as a parameter to prevent accidental use
     * Decentralizes the contract, this operation cannot be undone
     * @param _dac `0xdac` has to be entered for this function to work
     */
    removeOwnership(
      _dac: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * Checks to see if `_token` is in the blacklist of tokens
     * @param _token the token address being queried
     * @returns False if `_token` is in the blacklist and can't be taken out of  the contract via the `escapeHatch()`
     */
    isTokenEscapable(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * The `escapeHatch()` should only be called as a last resort if a security issue is uncovered or something unexpected happened
     * @param _token to transfer, use 0x0 for ether
     */
    escapeHatch(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * Changes the address assigned to call `escapeHatch()`
     * @param _newEscapeHatchCaller The address of a trusted account or  contract to call `escapeHatch()` to send the value in this contract to  the `escapeHatchDestination`; it would be ideal that `escapeHatchCaller`  cannot move funds out of `escapeHatchDestination`
     */
    changeHatchEscapeCaller(
      _newEscapeHatchCaller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Can only be called by the `newOwnerCandidate`, accepts the  transfer of ownership
     */
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * In this 2nd option for ownership transfer `changeOwnership()` can  be called and it will immediately assign ownership to the `newOwner`
     * `owner` can step down and assign some other address to this role
     * @param _newOwner The address of the new owner
     */
    changeOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    escapeHatchCaller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    escapeHatchDestination(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newOwnerCandidate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    /**
     * In this 1st option for ownership transfer `proposeOwnership()` must  be called first by the current `owner` then `acceptOwnership()` must be  called by the `newOwnerCandidate`
     * `onlyOwner` Proposes to transfer control of the contract to a  new owner
     * @param _newOwnerCandidate The address being proposed as the new owner
     */
    proposeOwnership(
      _newOwnerCandidate: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * In this 3rd option for ownership transfer `removeOwnership()` can  be called and it will immediately assign ownership to the 0x0 address;  it requires a 0xdece be input as a parameter to prevent accidental use
     * Decentralizes the contract, this operation cannot be undone
     * @param _dac `0xdac` has to be entered for this function to work
     */
    removeOwnership(
      _dac: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Checks to see if `_token` is in the blacklist of tokens
     * @param _token the token address being queried
     * @returns False if `_token` is in the blacklist and can't be taken out of  the contract via the `escapeHatch()`
     */
    isTokenEscapable(
      _token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * The `escapeHatch()` should only be called as a last resort if a security issue is uncovered or something unexpected happened
     * @param _token to transfer, use 0x0 for ether
     */
    escapeHatch(
      _token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Changes the address assigned to call `escapeHatch()`
     * @param _newEscapeHatchCaller The address of a trusted account or  contract to call `escapeHatch()` to send the value in this contract to  the `escapeHatchDestination`; it would be ideal that `escapeHatchCaller`  cannot move funds out of `escapeHatchDestination`
     */
    changeHatchEscapeCaller(
      _newEscapeHatchCaller: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
