/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface APMRegistryConstantsInterface extends utils.Interface {
  functions: {
    "REPO_APP_NAME()": FunctionFragment;
    "APM_APP_NAME()": FunctionFragment;
    "ENS_SUB_APP_NAME()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "REPO_APP_NAME"
      | "APM_APP_NAME"
      | "ENS_SUB_APP_NAME"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "REPO_APP_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "APM_APP_NAME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ENS_SUB_APP_NAME",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "REPO_APP_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "APM_APP_NAME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ENS_SUB_APP_NAME",
    data: BytesLike
  ): Result;

  events: {};
}

export interface APMRegistryConstants extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: APMRegistryConstantsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    REPO_APP_NAME(overrides?: CallOverrides): Promise<[string]>;

    APM_APP_NAME(overrides?: CallOverrides): Promise<[string]>;

    ENS_SUB_APP_NAME(overrides?: CallOverrides): Promise<[string]>;
  };

  REPO_APP_NAME(overrides?: CallOverrides): Promise<string>;

  APM_APP_NAME(overrides?: CallOverrides): Promise<string>;

  ENS_SUB_APP_NAME(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    REPO_APP_NAME(overrides?: CallOverrides): Promise<string>;

    APM_APP_NAME(overrides?: CallOverrides): Promise<string>;

    ENS_SUB_APP_NAME(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    REPO_APP_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    APM_APP_NAME(overrides?: CallOverrides): Promise<BigNumber>;

    ENS_SUB_APP_NAME(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    REPO_APP_NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    APM_APP_NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ENS_SUB_APP_NAME(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
