/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface CallsScriptInterface extends utils.Interface {
  functions: {
    "execScript(bytes,bytes,address[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "execScript"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execScript",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "execScript", data: BytesLike): Result;

  events: {
    "LogScriptCall(address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogScriptCall"): EventFragment;
}

export interface LogScriptCallEventObject {
  sender: string;
  src: string;
  dst: string;
}
export type LogScriptCallEvent = TypedEvent<
  [string, string, string],
  LogScriptCallEventObject
>;

export type LogScriptCallEventFilter = TypedEventFilter<LogScriptCallEvent>;

export interface CallsScript extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CallsScriptInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Executes a number of call scripts
     * @param _blacklist Addresses the script cannot call to, or will revert.
     * @param _input Input is ignored in callscript
     * @param _script [ specId (uint32) ] many calls with this structure ->   [ to (address: 20 bytes) ] [ calldataLength (uint32: 4 bytes) ] [ calldata (calldataLength bytes) ]
     * @returns always returns empty byte array
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  /**
   * Executes a number of call scripts
   * @param _blacklist Addresses the script cannot call to, or will revert.
   * @param _input Input is ignored in callscript
   * @param _script [ specId (uint32) ] many calls with this structure ->   [ to (address: 20 bytes) ] [ calldataLength (uint32: 4 bytes) ] [ calldata (calldataLength bytes) ]
   * @returns always returns empty byte array
   */
  execScript(
    _script: PromiseOrValue<BytesLike>,
    _input: PromiseOrValue<BytesLike>,
    _blacklist: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Executes a number of call scripts
     * @param _blacklist Addresses the script cannot call to, or will revert.
     * @param _input Input is ignored in callscript
     * @param _script [ specId (uint32) ] many calls with this structure ->   [ to (address: 20 bytes) ] [ calldataLength (uint32: 4 bytes) ] [ calldata (calldataLength bytes) ]
     * @returns always returns empty byte array
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "LogScriptCall(address,address,address)"(
      sender?: PromiseOrValue<string> | null,
      src?: PromiseOrValue<string> | null,
      dst?: PromiseOrValue<string> | null
    ): LogScriptCallEventFilter;
    LogScriptCall(
      sender?: PromiseOrValue<string> | null,
      src?: PromiseOrValue<string> | null,
      dst?: PromiseOrValue<string> | null
    ): LogScriptCallEventFilter;
  };

  estimateGas: {
    /**
     * Executes a number of call scripts
     * @param _blacklist Addresses the script cannot call to, or will revert.
     * @param _input Input is ignored in callscript
     * @param _script [ specId (uint32) ] many calls with this structure ->   [ to (address: 20 bytes) ] [ calldataLength (uint32: 4 bytes) ] [ calldata (calldataLength bytes) ]
     * @returns always returns empty byte array
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Executes a number of call scripts
     * @param _blacklist Addresses the script cannot call to, or will revert.
     * @param _input Input is ignored in callscript
     * @param _script [ specId (uint32) ] many calls with this structure ->   [ to (address: 20 bytes) ] [ calldataLength (uint32: 4 bytes) ] [ calldata (calldataLength bytes) ]
     * @returns always returns empty byte array
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
