/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface DeployDelegateScriptInterface extends utils.Interface {
  functions: {
    "execScript(bytes,bytes,address[])": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "execScript"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execScript",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "execScript", data: BytesLike): Result;

  events: {};
}

export interface DeployDelegateScript extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DeployDelegateScriptInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Executes script by delegatecall into a deployed contract (exec() function)
     * @param _blacklist If any address is passed, will revert.
     * @param _input ABI encoded call to be made to contract (if empty executes default exec() function)
     * @param _script [ specId (uint32) ][ contractInitcode (bytecode) ]
     * @returns Call return data
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  /**
   * Executes script by delegatecall into a deployed contract (exec() function)
   * @param _blacklist If any address is passed, will revert.
   * @param _input ABI encoded call to be made to contract (if empty executes default exec() function)
   * @param _script [ specId (uint32) ][ contractInitcode (bytecode) ]
   * @returns Call return data
   */
  execScript(
    _script: PromiseOrValue<BytesLike>,
    _input: PromiseOrValue<BytesLike>,
    _blacklist: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Executes script by delegatecall into a deployed contract (exec() function)
     * @param _blacklist If any address is passed, will revert.
     * @param _input ABI encoded call to be made to contract (if empty executes default exec() function)
     * @param _script [ specId (uint32) ][ contractInitcode (bytecode) ]
     * @returns Call return data
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    /**
     * Executes script by delegatecall into a deployed contract (exec() function)
     * @param _blacklist If any address is passed, will revert.
     * @param _input ABI encoded call to be made to contract (if empty executes default exec() function)
     * @param _script [ specId (uint32) ][ contractInitcode (bytecode) ]
     * @returns Call return data
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Executes script by delegatecall into a deployed contract (exec() function)
     * @param _blacklist If any address is passed, will revert.
     * @param _input ABI encoded call to be made to contract (if empty executes default exec() function)
     * @param _script [ specId (uint32) ][ contractInitcode (bytecode) ]
     * @returns Call return data
     */
    execScript(
      _script: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _blacklist: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
