/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface EVMScriptRegistryFactoryInterface extends utils.Interface {
  functions: {
    "baseReg()": FunctionFragment;
    "baseDeployDel()": FunctionFragment;
    "EVMSCRIPT_REGISTRY_APP_ID()": FunctionFragment;
    "EVMSCRIPT_REGISTRY_APP()": FunctionFragment;
    "baseCalls()": FunctionFragment;
    "newAppProxyPinned(address,bytes32,bytes)": FunctionFragment;
    "newAppProxyPinned(address,bytes32)": FunctionFragment;
    "newAppProxy(address,bytes32)": FunctionFragment;
    "newAppProxy(address,bytes32,bytes)": FunctionFragment;
    "baseDel()": FunctionFragment;
    "newEVMScriptRegistry(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "baseReg"
      | "baseDeployDel"
      | "EVMSCRIPT_REGISTRY_APP_ID"
      | "EVMSCRIPT_REGISTRY_APP"
      | "baseCalls"
      | "newAppProxyPinned(address,bytes32,bytes)"
      | "newAppProxyPinned(address,bytes32)"
      | "newAppProxy(address,bytes32)"
      | "newAppProxy(address,bytes32,bytes)"
      | "baseDel"
      | "newEVMScriptRegistry"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "baseReg", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "baseDeployDel",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVMSCRIPT_REGISTRY_APP_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVMSCRIPT_REGISTRY_APP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "baseCalls", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newAppProxyPinned(address,bytes32,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "newAppProxyPinned(address,bytes32)",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "newAppProxy(address,bytes32)",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "newAppProxy(address,bytes32,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "baseDel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "newEVMScriptRegistry",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "baseReg", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "baseDeployDel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVMSCRIPT_REGISTRY_APP_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVMSCRIPT_REGISTRY_APP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseCalls", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newAppProxyPinned(address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newAppProxyPinned(address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newAppProxy(address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newAppProxy(address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "baseDel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "newEVMScriptRegistry",
    data: BytesLike
  ): Result;

  events: {
    "NewAppProxy(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewAppProxy"): EventFragment;
}

export interface NewAppProxyEventObject {
  proxy: string;
}
export type NewAppProxyEvent = TypedEvent<[string], NewAppProxyEventObject>;

export type NewAppProxyEventFilter = TypedEventFilter<NewAppProxyEvent>;

export interface EVMScriptRegistryFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EVMScriptRegistryFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    baseReg(overrides?: CallOverrides): Promise<[string]>;

    baseDeployDel(overrides?: CallOverrides): Promise<[string]>;

    EVMSCRIPT_REGISTRY_APP_ID(overrides?: CallOverrides): Promise<[string]>;

    EVMSCRIPT_REGISTRY_APP(overrides?: CallOverrides): Promise<[string]>;

    baseCalls(overrides?: CallOverrides): Promise<[string]>;

    "newAppProxyPinned(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "newAppProxyPinned(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "newAppProxy(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "newAppProxy(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    baseDel(overrides?: CallOverrides): Promise<[string]>;

    newEVMScriptRegistry(
      _dao: PromiseOrValue<string>,
      _root: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  baseReg(overrides?: CallOverrides): Promise<string>;

  baseDeployDel(overrides?: CallOverrides): Promise<string>;

  EVMSCRIPT_REGISTRY_APP_ID(overrides?: CallOverrides): Promise<string>;

  EVMSCRIPT_REGISTRY_APP(overrides?: CallOverrides): Promise<string>;

  baseCalls(overrides?: CallOverrides): Promise<string>;

  "newAppProxyPinned(address,bytes32,bytes)"(
    _kernel: PromiseOrValue<string>,
    _appId: PromiseOrValue<BytesLike>,
    _initializePayload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "newAppProxyPinned(address,bytes32)"(
    _kernel: PromiseOrValue<string>,
    _appId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "newAppProxy(address,bytes32)"(
    _kernel: PromiseOrValue<string>,
    _appId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "newAppProxy(address,bytes32,bytes)"(
    _kernel: PromiseOrValue<string>,
    _appId: PromiseOrValue<BytesLike>,
    _initializePayload: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  baseDel(overrides?: CallOverrides): Promise<string>;

  newEVMScriptRegistry(
    _dao: PromiseOrValue<string>,
    _root: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    baseReg(overrides?: CallOverrides): Promise<string>;

    baseDeployDel(overrides?: CallOverrides): Promise<string>;

    EVMSCRIPT_REGISTRY_APP_ID(overrides?: CallOverrides): Promise<string>;

    EVMSCRIPT_REGISTRY_APP(overrides?: CallOverrides): Promise<string>;

    baseCalls(overrides?: CallOverrides): Promise<string>;

    "newAppProxyPinned(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "newAppProxyPinned(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "newAppProxy(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "newAppProxy(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    baseDel(overrides?: CallOverrides): Promise<string>;

    newEVMScriptRegistry(
      _dao: PromiseOrValue<string>,
      _root: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "NewAppProxy(address)"(proxy?: null): NewAppProxyEventFilter;
    NewAppProxy(proxy?: null): NewAppProxyEventFilter;
  };

  estimateGas: {
    baseReg(overrides?: CallOverrides): Promise<BigNumber>;

    baseDeployDel(overrides?: CallOverrides): Promise<BigNumber>;

    EVMSCRIPT_REGISTRY_APP_ID(overrides?: CallOverrides): Promise<BigNumber>;

    EVMSCRIPT_REGISTRY_APP(overrides?: CallOverrides): Promise<BigNumber>;

    baseCalls(overrides?: CallOverrides): Promise<BigNumber>;

    "newAppProxyPinned(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "newAppProxyPinned(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "newAppProxy(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "newAppProxy(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    baseDel(overrides?: CallOverrides): Promise<BigNumber>;

    newEVMScriptRegistry(
      _dao: PromiseOrValue<string>,
      _root: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    baseReg(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseDeployDel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    EVMSCRIPT_REGISTRY_APP_ID(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    EVMSCRIPT_REGISTRY_APP(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baseCalls(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "newAppProxyPinned(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "newAppProxyPinned(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "newAppProxy(address,bytes32)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "newAppProxy(address,bytes32,bytes)"(
      _kernel: PromiseOrValue<string>,
      _appId: PromiseOrValue<BytesLike>,
      _initializePayload: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    baseDel(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newEVMScriptRegistry(
      _dao: PromiseOrValue<string>,
      _root: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
