/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IAppProxyInterface extends utils.Interface {
  functions: {
    "isUpgradeable()": FunctionFragment;
    "getCode()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "isUpgradeable" | "getCode"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isUpgradeable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getCode", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "isUpgradeable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCode", data: BytesLike): Result;

  events: {};
}

export interface IAppProxy extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAppProxyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isUpgradeable(overrides?: CallOverrides): Promise<[boolean]>;

    getCode(overrides?: CallOverrides): Promise<[string]>;
  };

  isUpgradeable(overrides?: CallOverrides): Promise<boolean>;

  getCode(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    isUpgradeable(overrides?: CallOverrides): Promise<boolean>;

    getCode(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    isUpgradeable(overrides?: CallOverrides): Promise<BigNumber>;

    getCode(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isUpgradeable(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCode(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
