/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IKernelInterface extends utils.Interface {
  functions: {
    "acl()": FunctionFragment;
    "hasPermission(address,address,bytes32,bytes)": FunctionFragment;
    "setApp(bytes32,bytes32,address)": FunctionFragment;
    "getApp(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "acl" | "hasPermission" | "setApp" | "getApp"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "acl", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasPermission",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setApp",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getApp",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "acl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setApp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getApp", data: BytesLike): Result;

  events: {
    "SetApp(bytes32,bytes32,bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetApp"): EventFragment;
}

export interface SetAppEventObject {
  namespace: string;
  name: string;
  id: string;
  app: string;
}
export type SetAppEvent = TypedEvent<
  [string, string, string, string],
  SetAppEventObject
>;

export type SetAppEventFilter = TypedEventFilter<SetAppEvent>;

export interface IKernel extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IKernelInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acl(overrides?: CallOverrides): Promise<[string]>;

    hasPermission(
      who: PromiseOrValue<string>,
      where: PromiseOrValue<string>,
      what: PromiseOrValue<BytesLike>,
      how: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    setApp(
      namespace: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      app: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getApp(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  acl(overrides?: CallOverrides): Promise<string>;

  hasPermission(
    who: PromiseOrValue<string>,
    where: PromiseOrValue<string>,
    what: PromiseOrValue<BytesLike>,
    how: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  setApp(
    namespace: PromiseOrValue<BytesLike>,
    name: PromiseOrValue<BytesLike>,
    app: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getApp(
    id: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    acl(overrides?: CallOverrides): Promise<string>;

    hasPermission(
      who: PromiseOrValue<string>,
      where: PromiseOrValue<string>,
      what: PromiseOrValue<BytesLike>,
      how: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    setApp(
      namespace: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      app: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    getApp(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "SetApp(bytes32,bytes32,bytes32,address)"(
      namespace?: PromiseOrValue<BytesLike> | null,
      name?: PromiseOrValue<BytesLike> | null,
      id?: PromiseOrValue<BytesLike> | null,
      app?: null
    ): SetAppEventFilter;
    SetApp(
      namespace?: PromiseOrValue<BytesLike> | null,
      name?: PromiseOrValue<BytesLike> | null,
      id?: PromiseOrValue<BytesLike> | null,
      app?: null
    ): SetAppEventFilter;
  };

  estimateGas: {
    acl(overrides?: CallOverrides): Promise<BigNumber>;

    hasPermission(
      who: PromiseOrValue<string>,
      where: PromiseOrValue<string>,
      what: PromiseOrValue<BytesLike>,
      how: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setApp(
      namespace: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      app: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getApp(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acl(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasPermission(
      who: PromiseOrValue<string>,
      where: PromiseOrValue<string>,
      what: PromiseOrValue<BytesLike>,
      how: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setApp(
      namespace: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<BytesLike>,
      app: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getApp(
      id: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
