/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface PublicResolverInterface extends utils.Interface {
  functions: {
    "supportsInterface(bytes4)": FunctionFragment;
    "addr(bytes32)": FunctionFragment;
    "setAddr(bytes32,address)": FunctionFragment;
    "content(bytes32)": FunctionFragment;
    "setContent(bytes32,bytes32)": FunctionFragment;
    "name(bytes32)": FunctionFragment;
    "setName(bytes32,string)": FunctionFragment;
    "ABI(bytes32,uint256)": FunctionFragment;
    "setABI(bytes32,uint256,bytes)": FunctionFragment;
    "pubkey(bytes32)": FunctionFragment;
    "setPubkey(bytes32,bytes32,bytes32)": FunctionFragment;
    "text(bytes32,string)": FunctionFragment;
    "setText(bytes32,string,string)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "supportsInterface"
      | "addr"
      | "setAddr"
      | "content"
      | "setContent"
      | "name"
      | "setName"
      | "ABI"
      | "setABI"
      | "pubkey"
      | "setPubkey"
      | "text"
      | "setText"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "addr",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddr",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "content",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setContent",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "name",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setName",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "ABI",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setABI",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "pubkey",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPubkey",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "text",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setText",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "content", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setContent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ABI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setABI", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pubkey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPubkey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "text", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setText", data: BytesLike): Result;

  events: {
    "AddrChanged(bytes32,address)": EventFragment;
    "ContentChanged(bytes32,bytes32)": EventFragment;
    "NameChanged(bytes32,string)": EventFragment;
    "ABIChanged(bytes32,uint256)": EventFragment;
    "PubkeyChanged(bytes32,bytes32,bytes32)": EventFragment;
    "TextChanged(bytes32,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddrChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContentChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NameChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ABIChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PubkeyChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TextChanged"): EventFragment;
}

export interface AddrChangedEventObject {
  node: string;
  a: string;
}
export type AddrChangedEvent = TypedEvent<
  [string, string],
  AddrChangedEventObject
>;

export type AddrChangedEventFilter = TypedEventFilter<AddrChangedEvent>;

export interface ContentChangedEventObject {
  node: string;
  hash: string;
}
export type ContentChangedEvent = TypedEvent<
  [string, string],
  ContentChangedEventObject
>;

export type ContentChangedEventFilter = TypedEventFilter<ContentChangedEvent>;

export interface NameChangedEventObject {
  node: string;
  name: string;
}
export type NameChangedEvent = TypedEvent<
  [string, string],
  NameChangedEventObject
>;

export type NameChangedEventFilter = TypedEventFilter<NameChangedEvent>;

export interface ABIChangedEventObject {
  node: string;
  contentType: BigNumber;
}
export type ABIChangedEvent = TypedEvent<
  [string, BigNumber],
  ABIChangedEventObject
>;

export type ABIChangedEventFilter = TypedEventFilter<ABIChangedEvent>;

export interface PubkeyChangedEventObject {
  node: string;
  x: string;
  y: string;
}
export type PubkeyChangedEvent = TypedEvent<
  [string, string, string],
  PubkeyChangedEventObject
>;

export type PubkeyChangedEventFilter = TypedEventFilter<PubkeyChangedEvent>;

export interface TextChangedEventObject {
  node: string;
  indexedKey: string;
  key: string;
}
export type TextChangedEvent = TypedEvent<
  [string, string, string],
  TextChangedEventObject
>;

export type TextChangedEventFilter = TypedEventFilter<TextChangedEvent>;

export interface PublicResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PublicResolverInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    /**
     * Returns true if the resolver implements the interface specified by the provided hash.
     * @param interfaceID The ID of the interface to check for.
     * @returns True if the contract implements the requested interface.
     */
    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    /**
     * Returns the address associated with an ENS node.
     * @param node The ENS node to query.
     * @returns The associated address.
     */
    addr(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { ret: string }>;

    /**
     * Sets the address associated with an ENS node. May only be called by the owner of that node in the ENS registry.
     * @param addr The address to set.
     * @param node The node to update.
     */
    setAddr(
      node: PromiseOrValue<BytesLike>,
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns the content hash associated with an ENS node. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param node The ENS node to query.
     * @returns The associated content hash.
     */
    content(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { ret: string }>;

    /**
     * Sets the content hash associated with an ENS node. May only be called by the owner of that node in the ENS registry. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param hash The content hash to set
     * @param node The node to update.
     */
    setContent(
      node: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns the name associated with an ENS node, for reverse records. Defined in EIP181.
     * @param node The ENS node to query.
     * @returns The associated name.
     */
    name(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { ret: string }>;

    /**
     * Sets the name associated with an ENS node, for reverse records. May only be called by the owner of that node in the ENS registry.
     * @param name The name to set.
     * @param node The node to update.
     */
    setName(
      node: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns the ABI associated with an ENS node. Defined in EIP205.
     * @param contentTypes A bitwise OR of the ABI formats accepted by the caller.
     * @param node The ENS node to query
     * @returns contentType The content type of the return valuedata The ABI data
     */
    ABI(
      node: PromiseOrValue<BytesLike>,
      contentTypes: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { contentType: BigNumber; data: string }>;

    /**
     * Sets the ABI associated with an ENS node. Nodes may have one ABI of each content type. To remove an ABI, set it to the empty string.
     * @param contentType The content type of the ABI
     * @param data The ABI data.
     * @param node The node to update.
     */
    setABI(
      node: PromiseOrValue<BytesLike>,
      contentType: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns the SECP256k1 public key associated with an ENS node. Defined in EIP 619.
     * @param node The ENS node to query
     * @returns x, y the X and Y coordinates of the curve point for the public key.
     */
    pubkey(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { x: string; y: string }>;

    /**
     * Sets the SECP256k1 public key associated with an ENS node.
     * @param node The ENS node to query
     * @param x the X coordinate of the curve point for the public key.
     * @param y the Y coordinate of the curve point for the public key.
     */
    setPubkey(
      node: PromiseOrValue<BytesLike>,
      x: PromiseOrValue<BytesLike>,
      y: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    /**
     * Returns the text data associated with an ENS node and key.
     * @param key The text data key to query.
     * @param node The ENS node to query.
     * @returns The associated text data.
     */
    text(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string] & { ret: string }>;

    /**
     * Sets the text data associated with an ENS node and key. May only be called by the owner of that node in the ENS registry.
     * @param key The key to set.
     * @param node The node to update.
     * @param value The text data value to set.
     */
    setText(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  /**
   * Returns true if the resolver implements the interface specified by the provided hash.
   * @param interfaceID The ID of the interface to check for.
   * @returns True if the contract implements the requested interface.
   */
  supportsInterface(
    interfaceID: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  /**
   * Returns the address associated with an ENS node.
   * @param node The ENS node to query.
   * @returns The associated address.
   */
  addr(
    node: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  /**
   * Sets the address associated with an ENS node. May only be called by the owner of that node in the ENS registry.
   * @param addr The address to set.
   * @param node The node to update.
   */
  setAddr(
    node: PromiseOrValue<BytesLike>,
    addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns the content hash associated with an ENS node. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
   * @param node The ENS node to query.
   * @returns The associated content hash.
   */
  content(
    node: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  /**
   * Sets the content hash associated with an ENS node. May only be called by the owner of that node in the ENS registry. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
   * @param hash The content hash to set
   * @param node The node to update.
   */
  setContent(
    node: PromiseOrValue<BytesLike>,
    hash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns the name associated with an ENS node, for reverse records. Defined in EIP181.
   * @param node The ENS node to query.
   * @returns The associated name.
   */
  name(
    node: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  /**
   * Sets the name associated with an ENS node, for reverse records. May only be called by the owner of that node in the ENS registry.
   * @param name The name to set.
   * @param node The node to update.
   */
  setName(
    node: PromiseOrValue<BytesLike>,
    name: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns the ABI associated with an ENS node. Defined in EIP205.
   * @param contentTypes A bitwise OR of the ABI formats accepted by the caller.
   * @param node The ENS node to query
   * @returns contentType The content type of the return valuedata The ABI data
   */
  ABI(
    node: PromiseOrValue<BytesLike>,
    contentTypes: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { contentType: BigNumber; data: string }>;

  /**
   * Sets the ABI associated with an ENS node. Nodes may have one ABI of each content type. To remove an ABI, set it to the empty string.
   * @param contentType The content type of the ABI
   * @param data The ABI data.
   * @param node The node to update.
   */
  setABI(
    node: PromiseOrValue<BytesLike>,
    contentType: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns the SECP256k1 public key associated with an ENS node. Defined in EIP 619.
   * @param node The ENS node to query
   * @returns x, y the X and Y coordinates of the curve point for the public key.
   */
  pubkey(
    node: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[string, string] & { x: string; y: string }>;

  /**
   * Sets the SECP256k1 public key associated with an ENS node.
   * @param node The ENS node to query
   * @param x the X coordinate of the curve point for the public key.
   * @param y the Y coordinate of the curve point for the public key.
   */
  setPubkey(
    node: PromiseOrValue<BytesLike>,
    x: PromiseOrValue<BytesLike>,
    y: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  /**
   * Returns the text data associated with an ENS node and key.
   * @param key The text data key to query.
   * @param node The ENS node to query.
   * @returns The associated text data.
   */
  text(
    node: PromiseOrValue<BytesLike>,
    key: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  /**
   * Sets the text data associated with an ENS node and key. May only be called by the owner of that node in the ENS registry.
   * @param key The key to set.
   * @param node The node to update.
   * @param value The text data value to set.
   */
  setText(
    node: PromiseOrValue<BytesLike>,
    key: PromiseOrValue<string>,
    value: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    /**
     * Returns true if the resolver implements the interface specified by the provided hash.
     * @param interfaceID The ID of the interface to check for.
     * @returns True if the contract implements the requested interface.
     */
    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    /**
     * Returns the address associated with an ENS node.
     * @param node The ENS node to query.
     * @returns The associated address.
     */
    addr(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Sets the address associated with an ENS node. May only be called by the owner of that node in the ENS registry.
     * @param addr The address to set.
     * @param node The node to update.
     */
    setAddr(
      node: PromiseOrValue<BytesLike>,
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns the content hash associated with an ENS node. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param node The ENS node to query.
     * @returns The associated content hash.
     */
    content(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Sets the content hash associated with an ENS node. May only be called by the owner of that node in the ENS registry. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param hash The content hash to set
     * @param node The node to update.
     */
    setContent(
      node: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns the name associated with an ENS node, for reverse records. Defined in EIP181.
     * @param node The ENS node to query.
     * @returns The associated name.
     */
    name(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Sets the name associated with an ENS node, for reverse records. May only be called by the owner of that node in the ENS registry.
     * @param name The name to set.
     * @param node The node to update.
     */
    setName(
      node: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns the ABI associated with an ENS node. Defined in EIP205.
     * @param contentTypes A bitwise OR of the ABI formats accepted by the caller.
     * @param node The ENS node to query
     * @returns contentType The content type of the return valuedata The ABI data
     */
    ABI(
      node: PromiseOrValue<BytesLike>,
      contentTypes: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { contentType: BigNumber; data: string }>;

    /**
     * Sets the ABI associated with an ENS node. Nodes may have one ABI of each content type. To remove an ABI, set it to the empty string.
     * @param contentType The content type of the ABI
     * @param data The ABI data.
     * @param node The node to update.
     */
    setABI(
      node: PromiseOrValue<BytesLike>,
      contentType: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns the SECP256k1 public key associated with an ENS node. Defined in EIP 619.
     * @param node The ENS node to query
     * @returns x, y the X and Y coordinates of the curve point for the public key.
     */
    pubkey(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, string] & { x: string; y: string }>;

    /**
     * Sets the SECP256k1 public key associated with an ENS node.
     * @param node The ENS node to query
     * @param x the X coordinate of the curve point for the public key.
     * @param y the Y coordinate of the curve point for the public key.
     */
    setPubkey(
      node: PromiseOrValue<BytesLike>,
      x: PromiseOrValue<BytesLike>,
      y: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    /**
     * Returns the text data associated with an ENS node and key.
     * @param key The text data key to query.
     * @param node The ENS node to query.
     * @returns The associated text data.
     */
    text(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    /**
     * Sets the text data associated with an ENS node and key. May only be called by the owner of that node in the ENS registry.
     * @param key The key to set.
     * @param node The node to update.
     * @param value The text data value to set.
     */
    setText(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      value: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AddrChanged(bytes32,address)"(
      node?: PromiseOrValue<BytesLike> | null,
      a?: null
    ): AddrChangedEventFilter;
    AddrChanged(
      node?: PromiseOrValue<BytesLike> | null,
      a?: null
    ): AddrChangedEventFilter;

    "ContentChanged(bytes32,bytes32)"(
      node?: PromiseOrValue<BytesLike> | null,
      hash?: null
    ): ContentChangedEventFilter;
    ContentChanged(
      node?: PromiseOrValue<BytesLike> | null,
      hash?: null
    ): ContentChangedEventFilter;

    "NameChanged(bytes32,string)"(
      node?: PromiseOrValue<BytesLike> | null,
      name?: null
    ): NameChangedEventFilter;
    NameChanged(
      node?: PromiseOrValue<BytesLike> | null,
      name?: null
    ): NameChangedEventFilter;

    "ABIChanged(bytes32,uint256)"(
      node?: PromiseOrValue<BytesLike> | null,
      contentType?: PromiseOrValue<BigNumberish> | null
    ): ABIChangedEventFilter;
    ABIChanged(
      node?: PromiseOrValue<BytesLike> | null,
      contentType?: PromiseOrValue<BigNumberish> | null
    ): ABIChangedEventFilter;

    "PubkeyChanged(bytes32,bytes32,bytes32)"(
      node?: PromiseOrValue<BytesLike> | null,
      x?: null,
      y?: null
    ): PubkeyChangedEventFilter;
    PubkeyChanged(
      node?: PromiseOrValue<BytesLike> | null,
      x?: null,
      y?: null
    ): PubkeyChangedEventFilter;

    "TextChanged(bytes32,string,string)"(
      node?: PromiseOrValue<BytesLike> | null,
      indexedKey?: PromiseOrValue<string> | null,
      key?: null
    ): TextChangedEventFilter;
    TextChanged(
      node?: PromiseOrValue<BytesLike> | null,
      indexedKey?: PromiseOrValue<string> | null,
      key?: null
    ): TextChangedEventFilter;
  };

  estimateGas: {
    /**
     * Returns true if the resolver implements the interface specified by the provided hash.
     * @param interfaceID The ID of the interface to check for.
     * @returns True if the contract implements the requested interface.
     */
    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Returns the address associated with an ENS node.
     * @param node The ENS node to query.
     * @returns The associated address.
     */
    addr(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Sets the address associated with an ENS node. May only be called by the owner of that node in the ENS registry.
     * @param addr The address to set.
     * @param node The node to update.
     */
    setAddr(
      node: PromiseOrValue<BytesLike>,
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * Returns the content hash associated with an ENS node. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param node The ENS node to query.
     * @returns The associated content hash.
     */
    content(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Sets the content hash associated with an ENS node. May only be called by the owner of that node in the ENS registry. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param hash The content hash to set
     * @param node The node to update.
     */
    setContent(
      node: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * Returns the name associated with an ENS node, for reverse records. Defined in EIP181.
     * @param node The ENS node to query.
     * @returns The associated name.
     */
    name(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Sets the name associated with an ENS node, for reverse records. May only be called by the owner of that node in the ENS registry.
     * @param name The name to set.
     * @param node The node to update.
     */
    setName(
      node: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * Returns the ABI associated with an ENS node. Defined in EIP205.
     * @param contentTypes A bitwise OR of the ABI formats accepted by the caller.
     * @param node The ENS node to query
     * @returns contentType The content type of the return valuedata The ABI data
     */
    ABI(
      node: PromiseOrValue<BytesLike>,
      contentTypes: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Sets the ABI associated with an ENS node. Nodes may have one ABI of each content type. To remove an ABI, set it to the empty string.
     * @param contentType The content type of the ABI
     * @param data The ABI data.
     * @param node The node to update.
     */
    setABI(
      node: PromiseOrValue<BytesLike>,
      contentType: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * Returns the SECP256k1 public key associated with an ENS node. Defined in EIP 619.
     * @param node The ENS node to query
     * @returns x, y the X and Y coordinates of the curve point for the public key.
     */
    pubkey(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Sets the SECP256k1 public key associated with an ENS node.
     * @param node The ENS node to query
     * @param x the X coordinate of the curve point for the public key.
     * @param y the Y coordinate of the curve point for the public key.
     */
    setPubkey(
      node: PromiseOrValue<BytesLike>,
      x: PromiseOrValue<BytesLike>,
      y: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    /**
     * Returns the text data associated with an ENS node and key.
     * @param key The text data key to query.
     * @param node The ENS node to query.
     * @returns The associated text data.
     */
    text(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    /**
     * Sets the text data associated with an ENS node and key. May only be called by the owner of that node in the ENS registry.
     * @param key The key to set.
     * @param node The node to update.
     * @param value The text data value to set.
     */
    setText(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    /**
     * Returns true if the resolver implements the interface specified by the provided hash.
     * @param interfaceID The ID of the interface to check for.
     * @returns True if the contract implements the requested interface.
     */
    supportsInterface(
      interfaceID: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the address associated with an ENS node.
     * @param node The ENS node to query.
     * @returns The associated address.
     */
    addr(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Sets the address associated with an ENS node. May only be called by the owner of that node in the ENS registry.
     * @param addr The address to set.
     * @param node The node to update.
     */
    setAddr(
      node: PromiseOrValue<BytesLike>,
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the content hash associated with an ENS node. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param node The ENS node to query.
     * @returns The associated content hash.
     */
    content(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Sets the content hash associated with an ENS node. May only be called by the owner of that node in the ENS registry. Note that this resource type is not standardized, and will likely change in future to a resource type based on multihash.
     * @param hash The content hash to set
     * @param node The node to update.
     */
    setContent(
      node: PromiseOrValue<BytesLike>,
      hash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the name associated with an ENS node, for reverse records. Defined in EIP181.
     * @param node The ENS node to query.
     * @returns The associated name.
     */
    name(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Sets the name associated with an ENS node, for reverse records. May only be called by the owner of that node in the ENS registry.
     * @param name The name to set.
     * @param node The node to update.
     */
    setName(
      node: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the ABI associated with an ENS node. Defined in EIP205.
     * @param contentTypes A bitwise OR of the ABI formats accepted by the caller.
     * @param node The ENS node to query
     * @returns contentType The content type of the return valuedata The ABI data
     */
    ABI(
      node: PromiseOrValue<BytesLike>,
      contentTypes: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Sets the ABI associated with an ENS node. Nodes may have one ABI of each content type. To remove an ABI, set it to the empty string.
     * @param contentType The content type of the ABI
     * @param data The ABI data.
     * @param node The node to update.
     */
    setABI(
      node: PromiseOrValue<BytesLike>,
      contentType: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the SECP256k1 public key associated with an ENS node. Defined in EIP 619.
     * @param node The ENS node to query
     * @returns x, y the X and Y coordinates of the curve point for the public key.
     */
    pubkey(
      node: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Sets the SECP256k1 public key associated with an ENS node.
     * @param node The ENS node to query
     * @param x the X coordinate of the curve point for the public key.
     * @param y the Y coordinate of the curve point for the public key.
     */
    setPubkey(
      node: PromiseOrValue<BytesLike>,
      x: PromiseOrValue<BytesLike>,
      y: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    /**
     * Returns the text data associated with an ENS node and key.
     * @param key The text data key to query.
     * @param node The ENS node to query.
     * @returns The associated text data.
     */
    text(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    /**
     * Sets the text data associated with an ENS node and key. May only be called by the owner of that node in the ENS registry.
     * @param key The key to set.
     * @param node The node to update.
     * @param value The text data value to set.
     */
    setText(
      node: PromiseOrValue<BytesLike>,
      key: PromiseOrValue<string>,
      value: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
