/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface ScriptHelpersInterface extends utils.Interface {
  functions: {
    "abiEncode(bytes,bytes,address[])": FunctionFragment;
    "memcpy(uint256,uint256,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "abiEncode" | "memcpy"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "abiEncode",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "memcpy",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "abiEncode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "memcpy", data: BytesLike): Result;

  events: {};
}

export interface ScriptHelpers extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ScriptHelpersInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    abiEncode(
      _a: PromiseOrValue<BytesLike>,
      _b: PromiseOrValue<BytesLike>,
      _c: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<[string] & { d: string }>;

    memcpy(
      _dest: PromiseOrValue<BigNumberish>,
      _src: PromiseOrValue<BigNumberish>,
      _len: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  abiEncode(
    _a: PromiseOrValue<BytesLike>,
    _b: PromiseOrValue<BytesLike>,
    _c: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<string>;

  memcpy(
    _dest: PromiseOrValue<BigNumberish>,
    _src: PromiseOrValue<BigNumberish>,
    _len: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    abiEncode(
      _a: PromiseOrValue<BytesLike>,
      _b: PromiseOrValue<BytesLike>,
      _c: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<string>;

    memcpy(
      _dest: PromiseOrValue<BigNumberish>,
      _src: PromiseOrValue<BigNumberish>,
      _len: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    abiEncode(
      _a: PromiseOrValue<BytesLike>,
      _b: PromiseOrValue<BytesLike>,
      _c: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    memcpy(
      _dest: PromiseOrValue<BigNumberish>,
      _src: PromiseOrValue<BigNumberish>,
      _len: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    abiEncode(
      _a: PromiseOrValue<BytesLike>,
      _b: PromiseOrValue<BytesLike>,
      _c: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    memcpy(
      _dest: PromiseOrValue<BigNumberish>,
      _src: PromiseOrValue<BigNumberish>,
      _len: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
