/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  DelegateScriptTarget,
  DelegateScriptTargetInterface,
} from "../../contracts_v0.4/DelegateScriptTarget";

const _abi = [
  {
    constant: false,
    inputs: [],
    name: "exec",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class DelegateScriptTarget__factory {
  static readonly abi = _abi;
  static createInterface(): DelegateScriptTargetInterface {
    return new utils.Interface(_abi) as DelegateScriptTargetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DelegateScriptTarget {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DelegateScriptTarget;
  }
}
