/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  EVMScriptRegistryConstants,
  EVMScriptRegistryConstantsInterface,
} from "../../contracts_v0.4/EVMScriptRegistryConstants";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "EVMSCRIPT_REGISTRY_APP_ID",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "EVMSCRIPT_REGISTRY_APP",
    outputs: [
      {
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6060604052341561000f57600080fd5b6101648061001e6000396000f30060606040526004361061004b5763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166360b1e05781146100505780639b3fdf4c14610075575b600080fd5b341561005b57600080fd5b610063610088565b60405190815260200160405180910390f35b341561008057600080fd5b6100636100bc565b6040517f65766d7265672e617261676f6e706d2e657468000000000000000000000000008152601301604051809103902081565b6040517f6170700000000000000000000000000000000000000000000000000000000000815260030160405180910390206040517f65766d7265672e617261676f6e706d2e65746800000000000000000000000000815260130160405180910390206040519182526020820152604090810190518091039020815600a165627a7a723058208f8f19b03b09fcbecb6fc0ae991855ac9a0b9e9c438ae82685933eb1c370c5200029";

type EVMScriptRegistryConstantsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EVMScriptRegistryConstantsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EVMScriptRegistryConstants__factory extends ContractFactory {
  constructor(...args: EVMScriptRegistryConstantsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<EVMScriptRegistryConstants> {
    return super.deploy(overrides || {}) as Promise<EVMScriptRegistryConstants>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): EVMScriptRegistryConstants {
    return super.attach(address) as EVMScriptRegistryConstants;
  }
  override connect(signer: Signer): EVMScriptRegistryConstants__factory {
    return super.connect(signer) as EVMScriptRegistryConstants__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EVMScriptRegistryConstantsInterface {
    return new utils.Interface(_abi) as EVMScriptRegistryConstantsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EVMScriptRegistryConstants {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as EVMScriptRegistryConstants;
  }
}
