/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEVMScriptExecutor,
  IEVMScriptExecutorInterface,
} from "../../contracts_v0.4/IEVMScriptExecutor";

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "script",
        type: "bytes",
      },
      {
        name: "input",
        type: "bytes",
      },
      {
        name: "blacklist",
        type: "address[]",
      },
    ],
    name: "execScript",
    outputs: [
      {
        name: "",
        type: "bytes",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEVMScriptExecutor__factory {
  static readonly abi = _abi;
  static createInterface(): IEVMScriptExecutorInterface {
    return new utils.Interface(_abi) as IEVMScriptExecutorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEVMScriptExecutor {
    return new Contract(address, _abi, signerOrProvider) as IEVMScriptExecutor;
  }
}
